server:
  port: 8005


spring:
  redis:
    database: 0
    host: localhost
    port: 6379
#    password: root #springboot-redis密码不要设置成纯数字

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: imoocnews.com
